import type { ReactNode } from "react";
import type { AppRouteDefinition } from "@/app/router/route-types";
import { FlutterScreenPage, type FlutterScreenDescriptor } from "@/shared/ui/flutter-screen-page";

type FlutterRouteConfig = FlutterScreenDescriptor & {
  requiresAuth: boolean;
  guestOnly?: boolean;
  layout: "app" | "auth" | "telegram";
};

const routes: FlutterRouteConfig[] = [
  {
    path: "/settings",
    title: "Settings",
    description: "Перенос экрана настроек из Flutter.",
    feature: "settings",
    flutterSource: "lib/features/settings/views/settings_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/lessons",
    title: "Lessons",
    description: "Каталог уроков и быстрый вход в lesson flow.",
    feature: "lessons",
    flutterSource: "lib/features/lessons/views/lessons_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/lesson-details",
    title: "Lesson Details",
    description: "Детали отдельного урока и actions по прогрессу.",
    feature: "lessons",
    flutterSource: "lib/features/lessons/views/lesson_details_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/challenges",
    title: "Challenges",
    description: "Перенос challenge-ленты и challenge progress flows.",
    feature: "challenges",
    flutterSource: "lib/features/challenges/views/challenges_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/challenge-detail",
    title: "Challenge Detail",
    description: "Экран деталей challenge и связанных subchallenge действий.",
    feature: "challenges",
    flutterSource: "lib/features/challenges/views/challenge_detail_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/resources",
    title: "Resources",
    description: "Основной экран дополнительных материалов.",
    feature: "resources",
    flutterSource: "lib/features/resources/views/resources_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/additional-resources",
    title: "Additional Resources",
    description: "Дополнительный ресурсный экран из Flutter feature resources.",
    feature: "resources",
    flutterSource: "lib/features/resources/views/additional_resources_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/marketplace",
    title: "Marketplace",
    description: "Каталог marketplace и торговые entry points.",
    feature: "marketplace",
    flutterSource: "lib/features/marketplace/views/marketplace_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/item-detail",
    title: "Item Detail",
    description: "Детали товара marketplace.",
    feature: "marketplace",
    flutterSource: "lib/features/marketplace/views/item_detail_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/room",
    title: "Room",
    description: "Комната и интерактивный canvas flow из Flutter.",
    feature: "room",
    flutterSource: "lib/features/room/views/room_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/referrals",
    title: "Referrals",
    description: "Реферальный экран с кодом, историей и уровнями.",
    feature: "referrals",
    flutterSource: "lib/features/referrals/views/referrals_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/notifications",
    title: "Notifications",
    description: "Основной notification screen, Flutter использовал design variant.",
    feature: "notifications",
    flutterSource: "lib/features/notifications/views/design_notifications_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/notifications/list",
    title: "Notifications List",
    description: "Листовой вариант notification UI из Flutter.",
    feature: "notifications",
    flutterSource: "lib/features/notifications/views/notifications_list_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/notifications/modern",
    title: "Modern Notifications",
    description: "Modern notification variant.",
    feature: "notifications",
    flutterSource: "lib/features/notifications/views/modern_notifications_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/notifications/clean",
    title: "Clean Notifications",
    description: "Clean notification variant.",
    feature: "notifications",
    flutterSource: "lib/features/notifications/views/clean_notifications_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/leaderboard",
    title: "Rating",
    description: "Основной leaderboard/rating экран.",
    feature: "leaderboard",
    flutterSource: "lib/features/leaderboard/views/rating_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/leaderboard/overview",
    title: "Leaderboard Overview",
    description: "Отдельный leaderboard overview screen из Flutter.",
    feature: "leaderboard",
    flutterSource: "lib/features/leaderboard/views/leaderboard_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/referral-leaderboard",
    title: "Referral Leaderboard",
    description: "Реферальный рейтинг пользователей.",
    feature: "leaderboard",
    flutterSource: "lib/features/leaderboard/views/referral_leaderboard_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/telegram-login",
    title: "Telegram Login",
    description: "Телеграм-логин форма из Flutter auth flow.",
    feature: "auth",
    flutterSource: "lib/features/auth/views/telegram_login_view.dart",
    requiresAuth: false,
    guestOnly: true,
    layout: "auth",
  },
  {
    path: "/telegram-code-verification",
    title: "Telegram Code Verification",
    description: "Подтверждение кода для Telegram auth flow.",
    feature: "auth",
    flutterSource: "lib/features/auth/views/telegram_code_verification_view.dart",
    requiresAuth: false,
    guestOnly: true,
    layout: "auth",
  },
  {
    path: "/login-form",
    title: "Login Form",
    description: "Отдельный Flutter экран формы логина.",
    feature: "auth",
    flutterSource: "lib/features/auth/views/login_form_view.dart",
    requiresAuth: false,
    guestOnly: true,
    layout: "auth",
  },
  {
    path: "/reset-password",
    title: "Reset Password",
    description: "Экран reset password из Flutter auth flow.",
    feature: "auth",
    flutterSource: "lib/features/auth/views/reset_password_view.dart",
    requiresAuth: false,
    guestOnly: true,
    layout: "auth",
  },
  {
    path: "/set-password",
    title: "Set Password",
    description: "Экран установки пароля из Flutter auth flow.",
    feature: "auth",
    flutterSource: "lib/features/auth/views/set_password_view.dart",
    requiresAuth: false,
    layout: "auth",
  },
  {
    path: "/account",
    title: "Account",
    description: "Экран управления аккаунтом из Flutter.",
    feature: "account",
    flutterSource: "lib/features/account/views/account_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/change-password",
    title: "Change Password",
    description: "Экран изменения пароля.",
    feature: "account",
    flutterSource: "lib/features/account/views/change_password_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/achievements",
    title: "Achievements",
    description: "Каталог и история достижений.",
    feature: "achievements",
    flutterSource: "lib/features/achievements/views/achievements_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/premium-subscription",
    title: "Premium Subscription",
    description: "Покупка и апгрейд подписки.",
    feature: "subscription",
    flutterSource: "lib/features/subscription/views/premium_subscription_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/subscription-history",
    title: "Subscription History",
    description: "История подписок и продлений.",
    feature: "subscription",
    flutterSource: "lib/features/subscription/views/subscription_history_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/subscription",
    title: "Subscription",
    description: "Общий subscription screen из Flutter.",
    feature: "subscription",
    flutterSource: "lib/features/subscription/views/subscription_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/levels",
    title: "Levels",
    description: "Уровни, опыт и progression screen.",
    feature: "levels",
    flutterSource: "lib/features/levels/views/levels_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/transactions",
    title: "Transactions",
    description: "Все транзакции пользователя.",
    feature: "transactions",
    flutterSource: "lib/features/transactions/views/transactions_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/transactions/xp",
    title: "XP Transactions",
    description: "История XP транзакций.",
    feature: "transactions",
    flutterSource: "lib/features/transactions/views/xp_transactions_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/transactions/coins",
    title: "Coins Transactions",
    description: "История coin транзакций.",
    feature: "transactions",
    flutterSource: "lib/features/transactions/views/coins_transactions_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/webview",
    title: "WebView",
    description: "WebView container screen из Flutter.",
    feature: "webview",
    flutterSource: "lib/features/webview/views/webview_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/quiz-detail",
    title: "Quiz Detail",
    description: "Подробности квиза перед прохождением.",
    feature: "quiz",
    flutterSource: "lib/features/quiz/views/quiz_detail_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/quiz-take",
    title: "Quiz Take",
    description: "Старт квиза и pre-take screen.",
    feature: "quiz",
    flutterSource: "lib/features/quiz/views/quiz_take_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/quiz-taking",
    title: "Quiz Taking",
    description: "Основной экран прохождения квиза.",
    feature: "quiz",
    flutterSource: "lib/features/quiz/views/quiz_taking_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/quiz-result",
    title: "Quiz Result",
    description: "Результаты прохождения квиза.",
    feature: "quiz",
    flutterSource: "lib/features/quiz/views/quiz_result_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/quiz-history",
    title: "Quiz History",
    description: "История попыток пользователя.",
    feature: "quiz",
    flutterSource: "lib/features/quiz/views/quiz_history_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/attempt-details",
    title: "Attempt Details",
    description: "Детали конкретной quiz attempt.",
    feature: "quiz",
    flutterSource: "lib/features/quiz/views/attempt_details_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/stream-chat-list",
    title: "Stream Chat List",
    description: "Список каналов и комнат чата.",
    feature: "chat",
    flutterSource: "lib/features/chat/views/stream_chat_list_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/stream-chat-channel",
    title: "Stream Chat Channel",
    description: "Экран отдельного chat channel.",
    feature: "chat",
    flutterSource: "lib/features/chat/views/stream_chat_channel_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/stream-chat-channel-info",
    title: "Global Chat Info",
    description: "Информация о chat channel и участниках.",
    feature: "chat",
    flutterSource: "lib/features/chat/views/global_chat_info_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/payment-methods",
    title: "Payment Methods",
    description: "Выбор способа оплаты.",
    feature: "payment",
    flutterSource: "lib/features/payment/views/payment_methods_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/payment-result",
    title: "Payment Result",
    description: "Результат оплаты.",
    feature: "payment",
    flutterSource: "lib/features/payment/views/payment_result_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/payment-success",
    title: "Payment Success",
    description: "Success screen после оплаты.",
    feature: "payment",
    flutterSource: "lib/features/payment/views/payment_success_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/payment-waiting",
    title: "Payment Waiting",
    description: "Ожидание подтверждения платежа.",
    feature: "payment",
    flutterSource: "lib/features/payment/views/payment_waiting_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/feedback",
    title: "Feedback",
    description: "Экран обратной связи пользователя.",
    feature: "feedback",
    flutterSource: "lib/features/feedback/views/feedback_view.dart",
    requiresAuth: true,
    layout: "app",
  },
  {
    path: "/profile/analytics",
    title: "Analytics",
    description: "Профильная аналитика пользователя.",
    feature: "profile",
    flutterSource: "lib/features/profile/views/analytics_view.dart",
    requiresAuth: true,
    layout: "app",
  },
];

export const flutterScreenRoutes: AppRouteDefinition[] = routes.map((route) => {
  const siblings = routes
    .filter((candidate) => candidate.feature === route.feature && candidate.path !== route.path)
    .map((candidate) => ({ title: candidate.title, path: candidate.path }));

  return {
    path: route.path,
    meta: {
      requiresAuth: route.requiresAuth,
      guestOnly: route.guestOnly,
      layout: route.layout,
    },
    element: <FlutterScreenPage {...route} siblings={siblings} />,
  };
});

export const flutterScreenIndex = routes.reduce<Record<string, FlutterRouteConfig>>((acc, route) => {
  acc[route.path] = route;
  return acc;
}, {});

export const withFlutterDescriptor = (path: string, element: ReactNode) => {
  const route = flutterScreenIndex[path];

  if (!route) {
    return element;
  }

  return (
    <>
      {element}
    </>
  );
};
