export const endpoints = {
  auth: {
    login: "/api/v1/auth/login",
    register: "/api/v1/auth/register",
    forgotPassword: "/api/v2/auth/forgot-password",
    resetPassword: "/api/v2/auth/reset-password",
    requestLoginByPhone: "/api/v2/auth/request-login",
    verifyLoginCode: "/api/v2/auth/verify",
    telegramConfirm: "/api/v2/auth/telegram-confirm",
    requestSetPassword: "/api/v2/auth/request-set-password",
    setPassword: "/api/v2/auth/set-password",
    setPasswordSimple: "/api/v2/auth/set-password-simple",
    changePassword: "/api/v2/auth/change-password",
    me: "/api/v1/auth/me",
    refresh: "/api/v1/auth/refresh",
    telegramAuth: "/api/v1/telegram/auth/telegram",
    subscriptionStatus: "/api/v1/auth/subscription",
  },
  announcements: {
    list: "/api/v1/announcements/",
  },
  notifications: {
    list: "/api/v2/notifications/",
    markRead: (id: string) => `/api/v2/notifications/${id}/read`,
    markAllRead: "/api/v2/notifications/read-all",
    delete: (id: string) => `/api/v2/notifications/${id}`,
    unreadCount: "/api/v2/notifications/unread-count",
  },
  payment: {
    plans: "/api/v1/payment/plans/active",
    createInvoice: "/api/v1/payment/invoices",
    invoiceLinks: (id: string) => `/api/v1/payment/invoices/${id}/links`,
    invoiceStatus: (id: string) => `/api/v1/payment/invoices/${id}/status`,
    subscriptions: "/api/v1/payment/subscriptions/",
    subscriptionHistory: "/api/v1/payment/subscriptions/history",
  },
  achievements: {
    catalog: "/api/v1/achievements/catalog",
    my: "/api/v1/achievements/my",
    earned: "/api/v1/achievements/my/earned",
    progress: (id: string) => `/api/v1/achievements/${id}/progress`,
    claim: (id: string) => `/api/v1/achievements/${id}/claim`,
  },
  leaderboard: {
    xp: "/api/v2/statistics/leaderboard/xp",
    coins: "/api/v2/statistics/leaderboard/coins",
    referrals: "/api/v2/statistics/leaderboard/referrals",
    myPositionXp: "/api/v2/statistics/my-position/xp",
    myStats: "/api/v2/statistics/my-statistics/",
  },
  referrals: {
    stats: "/api/v1/referrals/my-stats",
    history: "/api/v1/referrals/history",
    levels: "/api/v1/referrals/levels",
  },
  transactions: {
    list: "/api/v2/gamification/transactions/",
    xp: "/api/v2/gamification/transactions/xp",
    coins: "/api/v2/gamification/transactions/coins",
  },
  resources: {
    categories: "/api/v1/additional_resources/categories",
    list: "/api/v1/additional_resources/",
    detail: (id: string) => `/api/v1/additional_resources/${id}`,
  },
  chat: {
    token: "/api/v1/chat/token",
  },
  courses: {
    categories: "/api/v1/courses/categories",
    list: "/api/v1/courses/",
    detail: (courseId: string) => `/api/v1/courses/${courseId}`,
    stats: (courseId: string) => `/api/v1/courses/${courseId}/stats`,
  },
  challenges: {
    list: "/api/v1/challenges/",
    detail: (challengeId: string) => `/api/v1/challenges/${challengeId}`,
    start: (challengeId: string) => `/api/v1/challenges/${challengeId}/start`,
  },
  profile: {
    me: "/api/v1/auth/me",
  },
  miniApps: {
    list: "/api/v1/mini-apps",
    detail: (slug: string) => `/api/v1/mini-apps/${slug}`,
  },
  lessons: {
    byCourse: (courseId: string) => `/api/v1/lessons/by_course/${courseId}`,
    progressStats: (courseId: string) => `/api/v1/lessons/by_course/${courseId}/progress-stats`,
    detail: (lessonId: string) => `/api/v1/lessons/${lessonId}`,
    progressByLesson: (lessonId: string) => `/api/v1/lessons/progress/by_lesson/${lessonId}`,
    progressCreate: "/api/v1/lessons/progress",
    progressUpdate: (lessonProgressId: string) => `/api/v1/lessons/progress/${lessonProgressId}`,
    complete: (lessonId: string) => `/api/v1/lessons/progress/${lessonId}/complete`,
  },
  quiz: {
    byLesson: (lessonId: string) => `/api/v1/quiz/quizzes/lesson/${lessonId}`,
  },
} as const;
